backend:
  name: github
  repo: agata-makarewicz/agata-site

media_folder: "img"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Tel"
            name: "tel"
            widget: "string"
          - label: "Tel display"
            name: "tel_display"
            widget: "string"
